version: "3"

services:
  db1:
    image: postgres:14.6
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_INITDB_ARGS: "-E UTF8"
      TZ: "Asia/Tokyo"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    external: false
